<?php
$this->title = "Delete Website User";
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete
'<?php echo $this->login; ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
<input type="hidden" name="login" value="<?php echo $this->login; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>


