<?php
$this->title = "Websites";
$this->headTitle($this->title);
?>
<p>
<a href="<?php echo $this->url(array('controller'=>'website', 'action'=>'create'));?>">Add new website</a></p>
<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Url</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->websites as $website) : ?>
    <tr>
        <td><?php echo $this->escape($website->id);?></td>
        <td><?php echo $this->escape($website->name);?></td>
        <td><?php echo $this->escape($website->url);?></td>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'website', 'action'=>'update', 'id'=>$website->id));?>">Update</a>
            <a href="<?php echo $this->url(array('controller'=>'website', 'action'=>'delete', 'id'=>$website->id));?>">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

