<?php 
echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title>G&eacute;n&eacute;rateur de Boutique sur Internet</title>
  <?php echo $this->headLink()->appendStylesheet('/quickstart/public/css/global.css') ?>
  <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/main.css'); ?>
</head> 
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b><a href="http://maboutiki.localhost">MaBoutiki</a></b>&nbsp; &nbsp;


	<?php 
	$acl = new Model_Acl(); 
	$identity = Zend_Auth::getInstance()->getIdentity();
    $userid = $identity['id'];
	if( Zend_Auth::getInstance()->hasIdentity() && $acl->isAllowed( $identity['role'] ,'user','showmyprofile') ) : ?>
		<b><a href="/user/update/id/<?php echo $userid; ?>">My Profile</a></b>&nbsp; &nbsp;
	<?php endif; ?>
	<? if( Zend_Auth::getInstance()->hasIdentity() && $acl->isAllowed( $identity['role'] ,'user','showallusers') ) : ?>
		<b><a href="/user">Users</a></b>&nbsp; &nbsp;
	<?php endif; ?>


    <?if( Zend_Auth::getInstance()->hasIdentity() && $acl->isAllowed( $identity['role'] ,'website','showmenu') ) : ?>
		<b><a href="/website">Website</a></b>&nbsp; &nbsp;
	<?php endif; ?>


        <?php echo $this->loggedInUser(); ?>
    </div>    
</div>

<div><?php echo $this->layout()->content ?></div>
</body>
</html>
