<?php
$this->title = "Users";
$this->headTitle($this->title);
?>
<p>
<?php 
	$acl = new Model_Acl(); 
	$identity = Zend_Auth::getInstance()->getIdentity();
	if( Zend_Auth::getInstance()->hasIdentity() && $acl->isAllowed( $identity['role'] ,'user','create') ) : ?>
<a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'create'));?>">Add new user</a></p>
<table>
    <tr>
        <th>Id</th>
        <th>Login</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->users as $user) : ?>
    <tr>
        <td><?php echo $this->escape($user->id);?></td>
        <td><?php echo $this->escape($user->login);?></td>
        <td><?php echo $this->escape($user->firstname);?></td>
        <td><?php echo $this->escape($user->lastname);?></td>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'update', 'id'=>$user->id));?>">Update</a>
            <a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'delete', 'id'=>$user->id));?>">Delete</a>
            <a href="<?php echo $this->url(array('controller'=>'website', 'action'=>'delete', 'login'=>$user->login));?>">Delete Website</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>
