<?php
$this->title = "Delete Software";
$this->headTitle($this->title);
$software = get_object_vars($this->software[0]);
?>
<p>Are you sure that you want to delete
'<?php echo $this->escape($software['name'])?>' identified by '<?php echo $this->escape($software['url']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->usersoftware['id']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>


