<?php
$this->title = "Delete Software";
$this->headTitle($this->title);
$software = get_object_vars($this->software[0]);

$acl = new Model_Acl(); 
$identity = Zend_Auth::getInstance()->getIdentity();
$userid = $identity['id'];
?>
<br /><br />
<div id="view-content">
<p>
    <?php 
        echo "Installation '". $identity['login'] . "' website with software #" . $this->usersoftware['id'] . " named '" . $this->escape($software['name']) . "'" ; 
    ?>
</p>
</div>

<p>Are you sure that you want to install this software?
</p>
<form action="<?php echo $this->url(array('action'=>'install')); ?>" method="post">
<div>
<input type="hidden" name="login" value="<?php echo $identity['login']; ?>" />
<input type="hidden" name="userid" value="<?php echo $userid; ?>" />
<input type="hidden" name="usersoftwareid" value="<?php echo $this->usersoftware['id']; ?>" />
<input type="submit" name="ins" value="Yes" />
<input type="submit" name="ins" value="No" />
</div>
</form>

