<?php
$this->title = "Delete Software";
$this->headTitle($this->title);
$software = get_object_vars($this->software[0]);

$acl = new Model_Acl(); 
$identity = Zend_Auth::getInstance()->getIdentity();
$userid = $identity['id'];
?>
<br /><br />
<div id="view-content">
<p>
    <?php 
        echo "Installation '". $identity['login'] . "' website with software #" . $software['id'] . " named '" . $this->escape($software['name']) . "'" ; 
    ?>
</p>
</div>
<?php 
    // Check the software availability
    // By default only the "Joomla de base #2" is available

    if($software['id'] == 2) {
?>
<p>Are you sure that you want to install this software?
</p>
<form action="<?php echo $this->url(array('action'=>'install')); ?>" method="post">
<div>
<input type="hidden" name="softwareid" value="<?php echo $software['id']; ?>" />
<input type="submit" name="ins" value="Yes" />
<input type="submit" name="ins" value="No" />
</div>
</form>
<?php 
    }else{ 
        echo "Software not available<br/>";
    }
?>
