<?php
$this->title = "Delete Software";
$this->headTitle($this->title);
$software = get_object_vars($this->software[0]);

$acl = new Model_Acl(); 
$identity = Zend_Auth::getInstance()->getIdentity();
$userid = $identity['id'];
?>
<br /><br />
<div id="view-content">
<p>
    <?php 
        echo "Installation '". $identity['login'] . "' website with software #" . $this->usersoftware['id'] . " named '" . $this->escape($software['name']) . "'" ; 
    ?>
</p>
</div>


