<?php
$this->title = "Install Software";
$this->headTitle($this->title);

$acl = new Model_Acl(); 
$identity = Zend_Auth::getInstance()->getIdentity();
$userid = $identity['id'];
$login = $identity['login'];

?>
<br /><br />
<div id="view-content">
<p>
    <?php 
        
        echo "Progress installation for software #" . $this->softwareid . " for user #" . $userid . " named " . $login; 
    ?>
</p>
</div>

